# Generated by Django 5.0.1 on 2024-04-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="custumers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("email", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=30)),
                ("age", models.IntegerField()),
            ],
        ),
    ]
